#!/usr/bin/env python3
"""
基础CGI测试脚本 - 显示环境变量和基本信息
"""

import os
import sys

print("Content-Type: text/html")
print("")

# 获取环境变量
server_software = os.environ.get('SERVER_SOFTWARE', 'Unknown')
server_name = os.environ.get('SERVER_NAME', 'localhost')
server_port = os.environ.get('SERVER_PORT', '80')
request_method = os.environ.get('REQUEST_METHOD', 'GET')
script_name = os.environ.get('SCRIPT_NAME', '')
query_string = os.environ.get('QUERY_STRING', '')
content_type = os.environ.get('CONTENT_TYPE', '')
content_length = os.environ.get('CONTENT_LENGTH', '0')

print("""<!DOCTYPE html>
<html>
<head>
    <title>Basic CGI Test</title>
    <style>
        body { font-family: Arial, sans-serif; margin: 40px; }
        .success { color: green; }
        .info { color: blue; }
        table { border-collapse: collapse; width: 100%; }
        th, td { border: 1px solid #ddd; padding: 8px; text-align: left; }
        th { background-color: #f2f2f2; }
    </style>
</head>
<body>
    <h1 class="success">🎉 Basic CGI Test - SUCCESS</h1>

    <h2>Server Information:</h2>
    <ul>""")

print(f"        <li><strong>Server Software:</strong> {server_software}</li>")
print(f"        <li><strong>Server Name:</strong> {server_name}</li>")
print(f"        <li><strong>Server Port:</strong> {server_port}</li>")
print(f"        <li><strong>Request Method:</strong> {request_method}</li>")
print(f"        <li><strong>Script Name:</strong> {script_name}</li>")
print(f"        <li><strong>Query String:</strong> {query_string if query_string else '(empty)'}</li>")
print(f"        <li><strong>Content Type:</strong> {content_type if content_type else '(not set)'}</li>")
print(f"        <li><strong>Content Length:</strong> {content_length}</li>")

print("""    </ul>

    <h2>Environment Variables:</h2>
    <table>
        <tr><th>Variable</th><th>Value</th></tr>""")

# 显示重要的CGI环境变量
important_vars = [
    'REQUEST_METHOD', 'QUERY_STRING', 'CONTENT_TYPE', 'CONTENT_LENGTH',
    'SERVER_NAME', 'SERVER_PORT', 'SERVER_PROTOCOL', 'SERVER_SOFTWARE',
    'SCRIPT_NAME', 'PATH_INFO', 'REMOTE_ADDR', 'REMOTE_HOST',
    'HTTP_HOST', 'HTTP_USER_AGENT', 'HTTP_ACCEPT'
]

for var in important_vars:
    value = os.environ.get(var, '(not set)')
    print(f"        <tr><td>{var}</td><td>{value}</td></tr>")

print("""    </table>

    <h2 class="info">Query String Parsing:</h2>""")

if query_string:
    print("    <ul>")
    params = query_string.split('&')
    for param in params:
        if '=' in param:
            key, value = param.split('=', 1)
            print(f"        <li><strong>{key}:</strong> {value}</li>")
        else:
            print(f"        <li><strong>{param}:</strong> (no value)</li>")
    print("    </ul>")
else:
    print("    <p>(No query parameters)</p>")

print("""
    <hr>
    <p><small>Generated by cgi_basic.py - Basic CGI functionality test</small></p>
</body>
</html>""")