#!/bin/bash
# Shell脚本CGI - 展示系统信息和多语言CGI支持

# 输出HTTP头
echo "Content-Type: text/html"
echo ""

# 获取系统信息
HOSTNAME=$(hostname)
UPTIME=$(uptime)
DATE=$(date)
USER=$(whoami)
PWD_DIR=$(pwd)
KERNEL=$(uname -a)

# 输出HTML
cat << 'HTML'
<!DOCTYPE html>
<html>
<head>
    <title>Shell Script CGI - System Info</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 40px;
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
        }
        .container {
            background: rgba(255,255,255,0.1);
            padding: 30px;
            border-radius: 15px;
            backdrop-filter: blur(10px);
            box-shadow: 0 8px 32px rgba(0,0,0,0.3);
        }
        h1 { text-align: center; text-shadow: 2px 2px 4px rgba(0,0,0,0.5); }
        .info-grid {
            display: grid;
            grid-template-columns: 1fr;
            gap: 15px;
            margin: 20px 0;
        }
        .info-item {
            background: rgba(255,255,255,0.2);
            padding: 15px;
            border-radius: 8px;
            border-left: 4px solid #fff;
        }
        .label { font-weight: bold; color: #f0f0f0; }
        .value {
            margin-top: 5px;
            font-family: monospace;
            background: rgba(0,0,0,0.3);
            padding: 5px;
            border-radius: 4px;
        }
        .success { color: #90ee90; font-weight: bold; }
    </style>
</head>
<body>
    <div class="container">
        <h1>🐚 Shell Script CGI Test</h1>
        <p class="success">✅ Shell Script CGI is working!</p>

        <div class="info-grid">
HTML

# 输出系统信息
echo "            <div class=\"info-item\">"
echo "                <div class=\"label\">🖥️ Hostname:</div>"
echo "                <div class=\"value\">$HOSTNAME</div>"
echo "            </div>"

echo "            <div class=\"info-item\">"
echo "                <div class=\"label\">📅 Current Date:</div>"
echo "                <div class=\"value\">$DATE</div>"
echo "            </div>"

echo "            <div class=\"info-item\">"
echo "                <div class=\"label\">⏰ System Uptime:</div>"
echo "                <div class=\"value\">$UPTIME</div>"
echo "            </div>"

echo "            <div class=\"info-item\">"
echo "                <div class=\"label\">👤 Current User:</div>"
echo "                <div class=\"value\">$USER</div>"
echo "            </div>"

echo "            <div class=\"info-item\">"
echo "                <div class=\"label\">📁 Working Directory:</div>"
echo "                <div class=\"value\">$PWD_DIR</div>"
echo "            </div>"

echo "            <div class=\"info-item\">"
echo "                <div class=\"label\">🔧 Kernel Info:</div>"
echo "                <div class=\"value\">$KERNEL</div>"
echo "            </div>"

# 环境变量信息
echo "            <div class=\"info-item\">"
echo "                <div class=\"label\">🌐 CGI Environment:</div>"
echo "                <div class=\"value\">"
echo "                    REQUEST_METHOD: ${REQUEST_METHOD:-Not Set}<br>"
echo "                    QUERY_STRING: ${QUERY_STRING:-Empty}<br>"
echo "                    HTTP_USER_AGENT: ${HTTP_USER_AGENT:-Not Set}<br>"
echo "                    REMOTE_ADDR: ${REMOTE_ADDR:-Not Set}<br>"
echo "                    SERVER_SOFTWARE: ${SERVER_SOFTWARE:-Not Set}"
echo "                </div>"
echo "            </div>"

# 结束HTML
cat << 'HTML'
        </div>

        <div style="text-align: center; margin-top: 30px; padding: 20px; background: rgba(255,255,255,0.1); border-radius: 10px;">
            <h3>🚀 Multi-Language CGI Support Demo</h3>
            <p>Your webserv supports multiple CGI languages:</p>
            <div style="display: flex; justify-content: center; gap: 20px; flex-wrap: wrap; margin-top: 15px;">
                <span style="background: rgba(255,255,255,0.2); padding: 8px 15px; border-radius: 20px;">🐍 Python (.py)</span>
                <span style="background: rgba(255,255,255,0.2); padding: 8px 15px; border-radius: 20px;">🐚 Bash (.sh)</span>
                <span style="background: rgba(255,255,255,0.2); padding: 8px 15px; border-radius: 20px;">🐘 PHP (.php)</span>
                <span style="background: rgba(255,255,255,0.2); padding: 8px 15px; border-radius: 20px;">🐪 Perl (.pl)</span>
            </div>
        </div>

        <footer style="text-align: center; margin-top: 20px; font-size: 0.9em; opacity: 0.8;">
            Generated by Shell Script CGI - webserv/1.0
        </footer>
    </div>
</body>
</html>
HTML