#!/usr/bin/env python3

import os
import sys

print("Content-Type: text/html")
print("")
print("<html>")
print("<head><title>CGI Test</title></head>")
print("<body>")
print("<h1>🎉 CGI Works!</h1>")
print("<p>This page was generated by a Python CGI script.</p>")

print("<h2>Environment Variables:</h2>")
print("<ul>")
for key, value in sorted(os.environ.items()):
    if key.startswith(('REQUEST_', 'HTTP_', 'SERVER_', 'SCRIPT_', 'PATH_', 'QUERY_', 'CONTENT_', 'GATEWAY_')):
        print(f"<li><strong>{key}:</strong> {value}</li>")
print("</ul>")

print("<h2>Request Method:</h2>")
print(f"<p>{os.environ.get('REQUEST_METHOD', 'Unknown')}</p>")

print("</body>")
print("</html>")